Repository bytecodealliance/wasm-micro-runtime, pull requests merged in 2025-07, with the labels that each got.

#4433 wasi-nn: reduce code duplication a bit
  core/iwasm/libraries/wasi-nn/src/wasi_nn_backend.h
  core/iwasm/libraries/wasi-nn/src/wasi_nn_llamacpp.c
  core/iwasm/libraries/wasi-nn/src/wasi_nn_openvino.c
  core/iwasm/libraries/wasi-nn/src/wasi_nn_tensorflowlite.cpp
  core/iwasm/libraries/wasi-nn/src/wasi_nn_tensorflowlite.hpp
Labels: wasi-nn

#4434 wasi_nn_openvino.c: avoid self-assignment warning
  core/iwasm/libraries/wasi-nn/src/wasi_nn_openvino.c
Labels: wasi-nn

#4425 CI: add wamr_wasi_extensions to the release assets
  .github/workflows/build_wamr_wasi_extensions.yml
  .github/workflows/release_process.yml
Labels: wasi-nn

#4446 wasi_nn_llamacpp.c: explicitly reject unimplemented input index
  core/iwasm/libraries/wasi-nn/src/wasi_nn_llamacpp.c
Labels: wasi-nn

#4468 wasi-nn: do not pretend to support legacy abi in openvino and llamacpp
  core/iwasm/libraries/wasi-nn/src/wasi_nn_llamacpp.c
  core/iwasm/libraries/wasi-nn/src/wasi_nn_openvino.c
Labels: wasi-nn

#4488 posix os_socket_accept: stop assuming socklen_t is unsigned int
  core/shared/platform/common/posix/posix_socket.c
Labels: bug-fix

#4461 modify macro related to simde when WASM_OP_SELECT_128
  core/iwasm/compilation/aot_compiler.c
  core/iwasm/interpreter/wasm_interp_fast.c
  core/iwasm/interpreter/wasm_loader.c
  core/iwasm/interpreter/wasm_opcode.h
Labels: bug-fix

#4493 wamr-wasi-extensions: document
  wamr-wasi-extensions/README.md
Labels: enhancement

#4490 nn-cli: add an option to use load_by_name
  wamr-wasi-extensions/samples/nn-cli/main.c
Labels: enhancement, wasi-nn

#4492 wasi-nn: add a comment on load_by_name_with_config
  core/iwasm/libraries/wasi-nn/src/wasi_nn.c
Labels: enhancement, wasi-nn

#4498 lib-socket: make getaddrinfo return EAI_ values
  core/iwasm/libraries/lib-socket/inc/wasi_socket_ext.h
  core/iwasm/libraries/lib-socket/src/wasi/wasi_socket_ext.c
Labels: breaking-change

#4503 Add a CLI option to specify shared heap size on Windows platform
  product-mini/platforms/windows/main.c
Labels: enhancement

#4511 bump AOT_CURRENT_VERSION for extended-const
  core/config.h
  core/iwasm/aot/aot_loader.c
  doc/build_wasm_app.md
  test-tools/aot-analyzer/include/config.h
Labels: enhancement

#4508 lib-socket: implement gai_strerror
  core/iwasm/libraries/lib-socket/inc/wasi_socket_ext.h
  core/iwasm/libraries/lib-socket/src/wasi/wasi_socket_ext.c
Labels: new feature

#4499 Add CLI option for iwasm to create and attach shared heap to wasm app
  core/iwasm/common/wasm_memory.c
  product-mini/platforms/posix/main.c
Labels: enhancement

#4514 Use venv to install llvm dependencies and run build script
  wamr-compiler/build_llvm.sh
  wamr-compiler/build_llvm_arc.sh
  wamr-compiler/build_llvm_xtensa.sh
Labels: enhancement

#4512 Add regression test CI
  .github/workflows/compilation_on_android_ubuntu.yml
  tests/regression/ba-issues/run.py
Labels: enhancement

#4491 wasi-nn: fix buffer overruns in load_by_name/load_by_name_with_config
  core/iwasm/libraries/wasi-nn/src/wasi_nn.c
Labels: wasi-nn, bug-fix

#4522 Add validation for recursive type count in loader
  core/iwasm/interpreter/wasm_loader.c
Labels: bug-fix
