Repository bytecodealliance/wasm-micro-runtime, pull requests merged in 2025-08, with the labels that each got.

#4520 Add validation for rec indices in aot loader
  core/iwasm/aot/aot_loader.c
Labels: bug-fix

#4418 Avoid executable stack by marking that it's not required.
  core/iwasm/common/arch/fneh.txt
  core/iwasm/common/arch/invokeNative_aarch64.s
  core/iwasm/common/arch/invokeNative_aarch64_simd.s
  core/iwasm/common/arch/invokeNative_arc.s
  core/iwasm/common/arch/invokeNative_arm.s
  core/iwasm/common/arch/invokeNative_arm_vfp.s
  core/iwasm/common/arch/invokeNative_em64.s
  core/iwasm/common/arch/invokeNative_em64_simd.s
  core/iwasm/common/arch/invokeNative_ia32.s
  core/iwasm/common/arch/invokeNative_mips.s
  core/iwasm/common/arch/invokeNative_osx_universal.s
  core/iwasm/common/arch/invokeNative_thumb.s
  core/iwasm/common/arch/invokeNative_thumb_vfp.s
  core/iwasm/common/arch/invokeNative_xtensa.s
Labels: bug-fix

#4526 Fix parsing of multiple IPs in --addr-pool option
  product-mini/platforms/common/libc_wasi.c
Labels: bug-fix

#4486 Add inputs for optional WAMR releases in the release process workflow
  .github/workflows/release_process.yml
Labels: breaking-change

#4496 Always use release builds of pre-built dependency libraries on Windows
  build-scripts/config_common.cmake
  wamr-compiler/CMakeLists.txt
Labels: bug-fix

#4532 core/iwasm/libraries/lib-socket/test/nslookup.c: use gai_strerror
  core/iwasm/libraries/lib-socket/test/nslookup.c
Labels: enhancement

#4534 wasi-nn: fix set_input memory address validation for the legacy abi
  core/iwasm/libraries/wasi-nn/src/utils/wasi_nn_app_native.c
Labels: wasi-nn, bug-fix

#4540 wamr-compiler: add --llvm-version option
  wamr-compiler/main.c
Labels: new feature

#4536 Add validation for struct field type in loader
  core/iwasm/aot/aot_loader.c
  core/iwasm/common/wasm_loader_common.c
  core/iwasm/common/wasm_loader_common.h
  core/iwasm/interpreter/wasm_loader.c
Labels: bug-fix

#4529 docs: add templates in runbook
  doc/security_issue_runbook.md
Labels: enhancement

#4500 Add new relocation type for aot
  core/iwasm/aot/aot_loader.c
  core/iwasm/aot/arch/aot_reloc_x86_64.c
Labels: enhancement

#4552 wasi_socket_ext.c: fix a typo in a comment
  core/iwasm/libraries/lib-socket/src/wasi/wasi_socket_ext.c
Labels: bug-fix

#4550 Add validtion for parent_type_idx
  core/iwasm/aot/aot_loader.c
Labels: bug-fix

#4564 wasi_nn_onnx.cpp: fix debug build
  core/iwasm/libraries/wasi-nn/src/wasi_nn_onnx.cpp
Labels: wasi-nn, bug-fix

#4546 Fix integer overflow in GC threshold calculation
  core/shared/mem-alloc/ems/ems_gc_internal.h
Labels: bug-fix
