Repository bytecodealliance/wasm-micro-runtime, pull requests merged in 2025-09, with the labels that each got.

#4549 Fix potential overflow in memory size calculation
  core/iwasm/aot/aot_runtime.c
  core/iwasm/interpreter/wasm_runtime.c
Labels: bug-fix

#4535 wasi-nn: add a missing address validation for get_output
  core/iwasm/libraries/wasi-nn/src/wasi_nn.c
Labels: wasi-nn, bug-fix

#4604 Fix the source_all override in platform_api_math.cmake for alios, riot, rt-thread, and zephyr platforms
  core/shared/platform/common/math/platform_api_math.cmake
Labels: bug-fix

#4397 Turn warnings into errors in CI
  .github/workflows/compilation_on_android_ubuntu.yml
  .github/workflows/compilation_on_macos.yml
  CMakeLists.txt
  build-scripts/config_common.cmake
  build-scripts/runtime_lib.cmake
  build-scripts/warnings.cmake
  product-mini/platforms/android/CMakeLists.txt
  product-mini/platforms/cosmopolitan/CMakeLists.txt
  product-mini/platforms/ios/CMakeLists.txt
  product-mini/platforms/linux/CMakeLists.txt
  product-mini/platforms/windows/CMakeLists.txt
  samples/basic/CMakeLists.txt
  samples/debug-tools/CMakeLists.txt
  samples/file/src/CMakeLists.txt
  samples/inst-context-threads/CMakeLists.txt
  samples/inst-context/CMakeLists.txt
  samples/multi-module/CMakeLists.txt
  samples/multi-thread/CMakeLists.txt
  samples/native-lib/CMakeLists.txt
  samples/native-stack-overflow/CMakeLists.txt
  samples/ref-types/CMakeLists.txt
  samples/shared-heap/CMakeLists.txt
  samples/shared-module/CMakeLists.txt
  samples/socket-api/CMakeLists.txt
  samples/spawn-thread/CMakeLists.txt
  samples/terminate/CMakeLists.txt
  samples/wasi-threads/CMakeLists.txt
  samples/wasm-c-api-imports/CMakeLists.txt
  samples/wasm-c-api/CMakeLists.txt
  test-tools/aot-analyzer/CMakeLists.txt
  tests/standalone/test-invoke-native/CMakeLists.txt
  tests/standalone/test-module-malloc/CMakeLists.txt
  tests/standalone/test-running-modes/c-embed/CMakeLists.txt
  tests/unit/wasm-c-api/CMakeLists.txt
  wamr-compiler/CMakeLists.txt
Labels: breaking-change

#4613 wasi-nn: retire is_model_loaded flag
  core/iwasm/libraries/wasi-nn/src/wasi_nn.c
  core/iwasm/libraries/wasi-nn/src/wasi_nn_private.h
Labels: enhancement, wasi-nn

#4611 libc-wasi: add missing pointer validations to socket functions
  core/iwasm/libraries/libc-wasi/libc_wasi_wrapper.c
Labels: enhancement

#4593 sync iwasm between windows and posix a bit
  product-mini/platforms/posix/main.c
  product-mini/platforms/windows/main.c
Labels: enhancement

#4571 Add micro `WAMR_BUILD_LIME1` to enable minimal lime1 feature set
  .github/workflows/compilation_on_android_ubuntu.yml
  build-scripts/config_common.cmake
  core/config.h
  core/iwasm/compilation/aot_compiler.c
  core/iwasm/compilation/aot_emit_memory.c
  core/iwasm/compilation/aot_emit_memory.h
  core/iwasm/compilation/aot_llvm.c
  core/iwasm/compilation/aot_llvm.h
  core/iwasm/fast-jit/fe/jit_emit_memory.c
  core/iwasm/fast-jit/fe/jit_emit_memory.h
  core/iwasm/fast-jit/jit_frontend.c
  core/iwasm/include/aot_comp_option.h
  core/iwasm/interpreter/wasm_interp_classic.c
  core/iwasm/interpreter/wasm_interp_fast.c
  core/iwasm/interpreter/wasm_loader.c
  core/iwasm/interpreter/wasm_mini_loader.c
  doc/build_wamr.md
  doc/build_wasm_app.md
  wamr-compiler/CMakeLists.txt
  wamr-compiler/main.c
Labels: new feature
